### ISSUE TITLE
Create basic structure

### ISSUE THREAD

**Issue by voryzhen** [ZakharKr/NaGiBaToR_500000#1]
1. Create basic structure:

- index.html
- style.css
- index.js

2. include style.css and index.js into index.html

**Comment by voryzhen** [comment]
Ты чё, пес ?!

**Comment by voryzhen** [comment]
Алоооо ?????

**Comment by voryzhen** [comment]
Где работа кафедры ?

**Comment by ZakharKr** [comment]
Done
